apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hanabi-ondc-sdk
  labels:
    app: hanabi-ondc-sdk
  name: hanabi-ondc-sdk
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hanabi-ondc-sdk
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hanabi-ondc-sdk
    spec:
      containers:
        - image: asia-south1-docker.pkg.dev/hanabi-bot/hana-repo/hanabi-ondc-sdk:b907755
          imagePullPolicy: IfNotPresent
          name: hanabi-ondc-sdk
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 100Mi
              memory: 750Mi
            requests:
              cpu: 250m
              ephemeral-storage: 100Mi
              memory: 750Mi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
